// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.beauty.domain;

import com.beauty.domain.BeautyOrder;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BeautyOrder_Roo_Configurable {
    
    declare @type: BeautyOrder: @Configurable;
    
}
